# Generated by Django 2.1.4 on 2019-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workedyears', models.FloatField(blank=True, db_column='workedYears', null=True)),
                ('salarybrutto', models.FloatField(blank=True, db_column='salaryBrutto', null=True)),
            ],
            options={
                'db_table': 'Salary',
                'managed': False,
            },
        ),
    ]
