# Generated by Django 2.1.4 on 2019-01-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={},
        ),
    ]
